/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Bel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AgregarPedido = new javax.swing.JMenuItem();
        AgregarProducto = new javax.swing.JMenuItem();
        AgregarMesa = new javax.swing.JMenuItem();
        AgregarMesero = new javax.swing.JMenuItem();
        AgregarReserva = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PrecioProducto = new javax.swing.JMenuItem();
        PedidosXMesa = new javax.swing.JMenuItem();
        pedidosXMesero = new javax.swing.JMenuItem();
        productoXCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        jMenu1.setText("Nuevos");

        AgregarPedido.setText("Agregar Pedido");
        AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarPedido);

        AgregarProducto.setText("Agregar Producto");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarProducto);

        AgregarMesa.setText("Agregar Mesa");
        AgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMesaActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarMesa);

        AgregarMesero.setText("Agregar Mesero");
        AgregarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMeseroActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarMesero);

        AgregarReserva.setText("Agregar Reserva");
        AgregarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarReservaActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarReserva);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        PrecioProducto.setText("Precios de Productos");
        PrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioProductoActionPerformed(evt);
            }
        });
        jMenu2.add(PrecioProducto);

        PedidosXMesa.setText("Pedidos por Mesa");
        PedidosXMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosXMesaActionPerformed(evt);
            }
        });
        jMenu2.add(PedidosXMesa);

        pedidosXMesero.setText("Pedidos por Mesero");
        pedidosXMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosXMeseroActionPerformed(evt);
            }
        });
        jMenu2.add(pedidosXMesero);

        productoXCategoria.setText("Productos por Categoria");
        productoXCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoXCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(productoXCategoria);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPedidoActionPerformed
         jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarPedido ap=new AgregarPedido();
      ap.setVisible(true);
      jEscritorio.add(ap);
      jEscritorio.moveToFront(ap);
    }//GEN-LAST:event_AgregarPedidoActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
       jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarProducto apr=new AgregarProducto();
      apr.setVisible(true);
      jEscritorio.add(apr);
      jEscritorio.moveToFront(apr);
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void AgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMesaActionPerformed

      jEscritorio.removeAll();
      jEscritorio.repaint();
     AgregarMesa am=new AgregarMesa();
      am.setVisible(true);
      jEscritorio.add(am);
      jEscritorio.moveToFront(am);
    }//GEN-LAST:event_AgregarMesaActionPerformed

    private void AgregarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMeseroActionPerformed
      jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarMesero ame=new AgregarMesero();
      ame.setVisible(true);
      jEscritorio.add(ame);
      jEscritorio.moveToFront(ame);
    }//GEN-LAST:event_AgregarMeseroActionPerformed

    private void AgregarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarReservaActionPerformed

      jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarReserva ar=new AgregarReserva();
      ar.setVisible(true);
      jEscritorio.add(ar);
      jEscritorio.moveToFront(ar);
    }//GEN-LAST:event_AgregarReservaActionPerformed

    private void PrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioProductoActionPerformed
      jEscritorio.removeAll();
      jEscritorio.repaint();
      PreciosDeProducto pp=new PreciosDeProducto();
      pp.setVisible(true);
      jEscritorio.add(pp);
      jEscritorio.moveToFront(pp);
        
    }//GEN-LAST:event_PrecioProductoActionPerformed

    private void PedidosXMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosXMesaActionPerformed
     jEscritorio.removeAll();
     jEscritorio.repaint();
      PedidosPorMesa ppm=new PedidosPorMesa();
      ppm.setVisible(true);
      jEscritorio.add(ppm);
      jEscritorio.moveToFront(ppm);        
    }//GEN-LAST:event_PedidosXMesaActionPerformed

    private void pedidosXMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosXMeseroActionPerformed
    jEscritorio.removeAll();
    jEscritorio.repaint();
    PedidosPorMesero ppme=new PedidosPorMesero();
    ppme.setVisible(true);
    jEscritorio.add(ppme);
    jEscritorio.moveToFront(ppme);
    }//GEN-LAST:event_pedidosXMeseroActionPerformed

    private void productoXCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoXCategoriaActionPerformed
    jEscritorio.removeAll();
    jEscritorio.repaint();
    ProductosPorCategoria ppc=new ProductosPorCategoria();
      ppc.setVisible(true);
    jEscritorio.add(ppc);
    jEscritorio.moveToFront(ppc);
    }//GEN-LAST:event_productoXCategoriaActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarMesa;
    private javax.swing.JMenuItem AgregarMesero;
    private javax.swing.JMenuItem AgregarPedido;
    private javax.swing.JMenuItem AgregarProducto;
    private javax.swing.JMenuItem AgregarReserva;
    private javax.swing.JMenuItem PedidosXMesa;
    private javax.swing.JMenuItem PrecioProducto;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem pedidosXMesero;
    private javax.swing.JMenuItem productoXCategoria;
    // End of variables declaration//GEN-END:variables
}
