/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Bel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagen/fondo.png"));
        Image image = icon.getImage();
        jEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AgregarPedido = new javax.swing.JMenuItem();
        AgregarProducto = new javax.swing.JMenuItem();
        AgregarMesa = new javax.swing.JMenuItem();
        AgregarMesero = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PrecioProducto = new javax.swing.JMenuItem();
        PedidosXMesa = new javax.swing.JMenuItem();
        pedidosXMesero = new javax.swing.JMenuItem();
        productoXCategoria = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("Agregar Pedido");

        jButton2.setText("Agregar Mesero");

        jButton3.setText("Agregar Mesa");

        jButton4.setText("Agregar Producto");

        jEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEscritorioLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEscritorioLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton4)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jMenu1.setText("Nuevos");

        AgregarPedido.setText("Agregar Pedido");
        AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarPedido);

        AgregarProducto.setText("Agregar Producto");
        AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarProducto);

        AgregarMesa.setText("Agregar Mesa");
        AgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMesaActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarMesa);

        AgregarMesero.setText("Agregar Mesero");
        AgregarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMeseroActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarMesero);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        PrecioProducto.setText("Precios de Productos");
        PrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioProductoActionPerformed(evt);
            }
        });
        jMenu2.add(PrecioProducto);

        PedidosXMesa.setText("Pedidos por Mesa");
        PedidosXMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosXMesaActionPerformed(evt);
            }
        });
        jMenu2.add(PedidosXMesa);

        pedidosXMesero.setText("Pedidos por Mesero");
        pedidosXMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosXMeseroActionPerformed(evt);
            }
        });
        jMenu2.add(pedidosXMesero);

        productoXCategoria.setText("Productos por Categoria");
        productoXCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoXCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(productoXCategoria);

        jMenuItem1.setText("PedidosXNumero");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPedidoActionPerformed
         jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarPedido ap=new AgregarPedido();
      ap.setVisible(true);
      jEscritorio.add(ap);
      jEscritorio.moveToFront(ap);
    }//GEN-LAST:event_AgregarPedidoActionPerformed

    private void AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoActionPerformed
       jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarProducto apr=new AgregarProducto();
      apr.setVisible(true);
      jEscritorio.add(apr);
      jEscritorio.moveToFront(apr);
    }//GEN-LAST:event_AgregarProductoActionPerformed

    private void AgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMesaActionPerformed

      jEscritorio.removeAll();
      jEscritorio.repaint();
     AgregarMesa am=new AgregarMesa();
      am.setVisible(true);
      jEscritorio.add(am);
      jEscritorio.moveToFront(am);
    }//GEN-LAST:event_AgregarMesaActionPerformed

    private void AgregarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMeseroActionPerformed
      jEscritorio.removeAll();
      jEscritorio.repaint();
      AgregarMesero ame=new AgregarMesero();
      ame.setVisible(true);
      jEscritorio.add(ame);
      jEscritorio.moveToFront(ame);
    }//GEN-LAST:event_AgregarMeseroActionPerformed

    private void PrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioProductoActionPerformed
      jEscritorio.removeAll();
      jEscritorio.repaint();
      PreciosDeProducto pp=new PreciosDeProducto();
      pp.setVisible(true);
      jEscritorio.add(pp);
      jEscritorio.moveToFront(pp);
        
    }//GEN-LAST:event_PrecioProductoActionPerformed

    private void PedidosXMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosXMesaActionPerformed
     jEscritorio.removeAll();
     jEscritorio.repaint();
      PedidosPorMesa ppm=new PedidosPorMesa();
      ppm.setVisible(true);
      jEscritorio.add(ppm);
      jEscritorio.moveToFront(ppm);        
    }//GEN-LAST:event_PedidosXMesaActionPerformed

    private void pedidosXMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosXMeseroActionPerformed
    jEscritorio.removeAll();
    jEscritorio.repaint();
    PedidosPorMesero ppme=new PedidosPorMesero();
    ppme.setVisible(true);
    jEscritorio.add(ppme);
    jEscritorio.moveToFront(ppme);
    }//GEN-LAST:event_pedidosXMeseroActionPerformed

    private void productoXCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoXCategoriaActionPerformed
    jEscritorio.removeAll();
    jEscritorio.repaint();
    ProductosPorCategoria ppc=new ProductosPorCategoria();
      ppc.setVisible(true);
    jEscritorio.add(ppc);
    jEscritorio.moveToFront(ppc);
    }//GEN-LAST:event_productoXCategoriaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    jEscritorio.repaint();
    PedidosXNumero pn=new PedidosXNumero();
    pn.setVisible(true);
    jEscritorio.add(pn);
    jEscritorio.moveToFront(pn);
        

    }//GEN-LAST:event_jMenuItem1ActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarMesa;
    private javax.swing.JMenuItem AgregarMesero;
    private javax.swing.JMenuItem AgregarPedido;
    private javax.swing.JMenuItem AgregarProducto;
    private javax.swing.JMenuItem PedidosXMesa;
    private javax.swing.JMenuItem PrecioProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem pedidosXMesero;
    private javax.swing.JMenuItem productoXCategoria;
    // End of variables declaration//GEN-END:variables

}
