/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Bel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagen/Menu.png"));
        Image image = icon.getImage();
        jEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        btnAgregarPedido = new javax.swing.JButton();
        bAgregarMesero = new javax.swing.JButton();
        btnAgregarMesa = new javax.swing.JButton();
        btnAgregarP = new javax.swing.JButton();
        btPreciosProductos = new javax.swing.JButton();
        btPedidosXmesa = new javax.swing.JButton();
        btPedidosXmesero = new javax.swing.JButton();
        btProductosXcategoria = new javax.swing.JButton();
        btPedidosXnumero = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarPedido.setText("Agregar Pedido");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });

        bAgregarMesero.setText("Agregar Mesero");
        bAgregarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarMeseroActionPerformed(evt);
            }
        });

        btnAgregarMesa.setText("Agregar Mesa");
        btnAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMesaActionPerformed(evt);
            }
        });

        btnAgregarP.setText("Agregar Producto");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });

        btPreciosProductos.setText("Precios Productos");
        btPreciosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreciosProductosActionPerformed(evt);
            }
        });

        btPedidosXmesa.setText("PedidosXmesa");
        btPedidosXmesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosXmesaActionPerformed(evt);
            }
        });

        btPedidosXmesero.setText("PedidosXmesero");
        btPedidosXmesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosXmeseroActionPerformed(evt);
            }
        });

        btProductosXcategoria.setText("ProductosXcategoria");
        btProductosXcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductosXcategoriaActionPerformed(evt);
            }
        });

        btPedidosXnumero.setText("PedidosXnumero");
        btPedidosXnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosXnumeroActionPerformed(evt);
            }
        });

        jEscritorio.setLayer(btnAgregarPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(bAgregarMesero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btnAgregarMesa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btnAgregarP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btPreciosProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btPedidosXmesa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btPedidosXmesero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btProductosXcategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(btPedidosXnumero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jEscritorioLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(bAgregarMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jEscritorioLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btProductosXcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btPedidosXmesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btPreciosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btPedidosXmesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jEscritorioLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAgregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jEscritorioLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btPedidosXnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPreciosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPedidosXmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPedidosXmesero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProductosXcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btPedidosXnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMesaActionPerformed
       
        jEscritorio.repaint();
        AgregarMesa am = new AgregarMesa();
        am.setVisible(true);
        jEscritorio.add(am);
        jEscritorio.moveToFront(am);
    }//GEN-LAST:event_btnAgregarMesaActionPerformed

    private void bAgregarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarMeseroActionPerformed
        
        jEscritorio.repaint();
        AgregarMesero ame = new AgregarMesero();
        ame.setVisible(true);
        jEscritorio.add(ame);
        jEscritorio.moveToFront(ame);
    }//GEN-LAST:event_bAgregarMeseroActionPerformed

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        
        
        jEscritorio.repaint();
        AgregarPedido ap = new AgregarPedido();
        ap.setVisible(true);
        jEscritorio.add(ap);
        jEscritorio.moveToFront(ap);
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
       
        jEscritorio.repaint();
        AgregarProducto apr = new AgregarProducto();
        apr.setVisible(true);
        jEscritorio.add(apr);
        jEscritorio.moveToFront(apr);
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btPreciosProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreciosProductosActionPerformed
     
        jEscritorio.repaint();
        PreciosDeProducto pp = new PreciosDeProducto();
        pp.setVisible(true);
        jEscritorio.add(pp);
        jEscritorio.moveToFront(pp);

    }//GEN-LAST:event_btPreciosProductosActionPerformed

    private void btPedidosXmesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosXmesaActionPerformed
        
        jEscritorio.repaint();
        PedidosPorMesa ppm = new PedidosPorMesa();
        ppm.setVisible(true);
        jEscritorio.add(ppm);
        jEscritorio.moveToFront(ppm);
    }//GEN-LAST:event_btPedidosXmesaActionPerformed

    private void btPedidosXmeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosXmeseroActionPerformed

  
        jEscritorio.repaint();
        PedidosPorMesero ame = new PedidosPorMesero();
        ame.setVisible(true);
        jEscritorio.add(ame);
        jEscritorio.moveToFront(ame);

    }//GEN-LAST:event_btPedidosXmeseroActionPerformed

    private void btProductosXcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductosXcategoriaActionPerformed

        
        jEscritorio.repaint();
        ProductosPorCategoria ppc = new ProductosPorCategoria();
        ppc.setVisible(true);
        jEscritorio.add(ppc);
        jEscritorio.moveToFront(ppc);

    }//GEN-LAST:event_btProductosXcategoriaActionPerformed

    private void btPedidosXnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosXnumeroActionPerformed

        jEscritorio.repaint();
        PedidosXNumero pn = new PedidosXNumero();
        pn.setVisible(true);
        jEscritorio.add(pn);
        jEscritorio.moveToFront(pn);

    }//GEN-LAST:event_btPedidosXnumeroActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarMesero;
    private javax.swing.JButton btPedidosXmesa;
    private javax.swing.JButton btPedidosXmesero;
    private javax.swing.JButton btPedidosXnumero;
    private javax.swing.JButton btPreciosProductos;
    private javax.swing.JButton btProductosXcategoria;
    private javax.swing.JButton btnAgregarMesa;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnAgregarP1;
    private javax.swing.JButton btnAgregarP2;
    private javax.swing.JButton btnAgregarPedido;
    public javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
